### PR TITLE
add healthcheck endpoint

### PR DESCRIPTION
**Pull request by yaron-idan**
Closing issue #338

### CODE REVIEW

**Comment by yaron-idan** [comment]
Hey @matthiasr, can I please get this reviewed?

**Comment by matthiasr** [comment]
Sorry about that, I was on vacation for a while and then the first week of work was wild.

For these simple health checks, I don't think we need a flag to turn them off. They don't expose anything, and who doesn't need them is free to ignore them. On the other hand, for consistency with prometheus/prometheus, would it make sense to also have a "ready" endpoint? When would that become active?

**Comment by yaron-idan** [comment]
Hey @matthiasr , thanks for your comments!
I see your point about the flag necessity, I've pushed a commit removing it.
Regarding the "ready" endpoint - contrary to prometheus, which requires it's TSDB backend to become ready before it can successfully serve queries and scrape targets, this exporter can receive metrics the moment it's webserver is able to listen for requests. That's why I thought it might be redundant to add it as well. I've added this endpoint as well, but for now it fully replicates the healthy endpoint (only returning a different text).
If you think there are further checks that should be done before the service is ready let me know and I'll try to dig into that.

**Review by matthiasr — APPROVED** [review]
Looks good, having them do the same thing is a good start. If we find situations where they should differ, we can add more checks. Can you add the DCO sign-off please?

**Pull request merged**
