### PR TITLE
Update prometheus/client_golang to v1.0.0

### PR DESCRIPTION
**Pull request by beorn7**
Signed-off-by: beorn7 <beorn@grafana.com>

### CODE REVIEW

**Comment by beorn7** [comment]
@matthiasr ping?
Or in case @matthiasr is currently not available, perhaps @simonpasquier as the master of modules could have a look?

**Comment by beorn7** [comment]
@simonpasquier , thanks for reviewing all the other PRs of this kind. Could you also look at this one? (@matthiasr seems to be unavailable right now.)

**Comment by beorn7** [comment]
Thanks. That was the last of the “update client_golang to v1” PRs. :tada:

**Comment by matthiasr** [comment]
Sorry, I was indeed out for a few days, thank you both for taking care of it!

**Pull request merged**
