### PR TITLE
Vendor dependencies

### LINKED ISSUE #29: Godep manifest and release
Please add godep manifest and make new release.
If checkout version 0.1.0 and try make `godep get` i get this result
```
github.com/howeyc/fsnotify (download)
github.com/prometheus/client_golang (download)
package github.com/prometheus/client_golang/model: cannot find package "github.com/prometheus/client_golang/model" in any of:
	/usr/local/go/src/github.com/prometheus/client_golang/model (from $GOROOT)
	/go/src/github.com/prometheus/client_golang/model (from $GOPATH)
github.com/beorn7/perks (download)
github.com/golang/protobuf (download)
github.com/prometheus/client_model (download)
github.com/prometheus/common (download)
github.com/matttproud/golang_protobuf_extensions (download)
github.com/prometheus/procfs (download)
godep: exit status 1
```

### PR DESCRIPTION
**Pull request by discordianfish**
This closes #29

### CODE REVIEW

**Comment by juliusv** [comment]
I wonder where the vendored `golang.org/x/...` dependencies come from. Neither the statsd exporter nor its other vendored libs import it.

**Comment by discordianfish** [comment]
@juliusv hrm weird.. I just did `govendor init && govendor add +external`. I thought that would include all used dependencies?

**Comment by juliusv** [comment]
Ah sorry. I grepped wrong.

```
vendor/github.com/Sirupsen/logrus/terminal_solaris.go
8:	"golang.org/x/sys/unix"
```

Grumble... so only because of Solaris, we have to pull in such a huge amount of code.

:+1: I guess. It's interesting that we don't have that in Prometheus yet. Maybe because the vendored logrus version is older there.

**Comment by sdurrheimer** [comment]
I don't see a `vendor.json`, is that normal ?

**Pull request merged**
