### PR TITLE
Added 'collector.disable-go-runtime-metrics' flag

### PR DESCRIPTION
**Pull request by Amir-Hadadi**
This flag controls go runtime metrics collection by the exporter.
The default scenario is collecting the go runtime metrics using the default go Prometheus client, using this flag means we want to disable collection. It defaults to false.
Discussion and more info is [here](https://groups.google.com/g/prometheus-developers/c/NHs1Mg3oGXA).

### CODE REVIEW

**Comment by Amir-Hadadi** [comment]
Subject about this is pending on Prometheus Developers

**Comment by beorn7** [comment]
As discussed in the linked mail thread, I believe we should do this in a consistent way between exporters, ideally in https://github.com/prometheus/exporter-toolkit . (Note that this PR does something different to the existing flag in node_exporter, both in behavior and name of the flag.)

**Comment by beorn7** [comment]
See also https://github.com/prometheus/exporter-toolkit/issues/119

**Comment by matthiasr** [comment]
Thank you @beorn7 – I agree that this should be directly in exporter-toolkit, and consistent across exporters. I'll close this PR not as a "I don't want this" but as a "please do this in exporter-toolkit instead, and we can then pick it up here" 😄

**Pull request closed without merging**
