### PR TITLE
Fixed docker run command

### PR DESCRIPTION
**Pull request by gbahrani**
1. Configuration file extension changed from .conf to .yml
2. Added missing dash (-) in statsd-exporter inputs

### CODE REVIEW

**Comment by matthiasr** [comment]
Thank you! Can you also add the sign-off to the commit? The details of the failed test document how to do that.

**Comment by gbahrani** [comment]
Done

**Comment by matthiasr** [comment]
Thank you!

**Comment by nakkurt** [comment]
@matthiasr I noticed the [Docker Library description for prom/statsd-exporter](https://hub.docker.com/r/prom/statsd-exporter) hasn't been updated with these `docker run ..` changes. 
Is there a way I could make a PR for that?

**Comment by matthiasr** [comment]
Thank you for the reminder! Unfortunately the Docker Hub/Quay descriptions are not currently updated automatically. I copied the current version of the README over to both.

**Pull request merged**
