### PR TITLE
feat: support inject global labels

### PR DESCRIPTION
**Pull request by shuxnhs**

### CODE REVIEW

**Comment by matthiasr** [comment]
Thank you for your PR! Unfortunately, as per the [exporter guidelines](https://prometheus.io/docs/instrumenting/writing_exporters/#target-labels-not-static-scraped-labels), this is not a feature that we will add to this exporter. As lined out in the guideline, use target relabeling instead.

**Comment by shuxnhs** [comment]
i know, but if your have many exporters in different regions, you can‘t use target relabeling to distinguish by the label. this is why i add this feature.

**Comment by matthiasr** [comment]
Distinguish regions by adding an external label to the regional Prometheus servers.

**Comment by shuxnhs** [comment]
ok, thank you～

**Pull request closed without merging**
