### PR TITLE
mapper cache: Add cache metrics for total gets and hits

### PR DESCRIPTION
**Pull request by bakins**
Add metrics to record mapper cache hits and total gets.

### CODE REVIEW

**Comment by brian-brazil** [comment]
Separate hits and total metrics are easier to work with, as you don't have to add before you divide.

**Comment by bakins** [comment]
@brian-brazil should we also have a separate metric for total cache Get requests?

**Comment by brian-brazil** [comment]
The total is the get requests.

**Comment by bakins** [comment]
> The total is the get requests.

Not sure I follow. Do we already have a metric that tracks total cache gets?

**Comment by bakins** [comment]
Refactored to have a metric for total gets and a metric for total hits.

Sorry, my mind is apparently still on holiday as it took me a bit to realize what you were suggesting @brian-brazil

**Comment by brian-brazil** [comment]
:+1:

**Comment by bakins** [comment]
@matthiasr changed the metrics names.

Note: the existing metric in mapper is named `statsd_exporter_cache_length` https://github.com/prometheus/statsd_exporter/blob/2e3d3ab962ec7c305e590dec4ffebc465a00c034/pkg/mapper/mapper_cache.go#L24

**Pull request merged**
