### PR TITLE
Increase receivable UDP datagram size to 65535 bytes.

### PR DESCRIPTION
**Pull request by juliusv**
Fixes https://github.com/prometheus/statsd_exporter/issues/35

### CODE REVIEW

**Comment by juliusv** [comment]
Or should this be even larger? Jumbo frames can be up to 9216 bytes.

**Comment by SuperQ** [comment]
Can we make this a flag?

**Comment by SuperQ** [comment]
Per https://github.com/prometheus/statsd_exporter/issues/35#issuecomment-215735556, let's make this 64kB.

**Comment by juliusv** [comment]
@SuperQ Updated to 65,535 bytes.

**Comment by SuperQ** [comment]
:+1:

**Pull request merged**
