### PR TITLE
Fix packet counting

### PR DESCRIPTION
**Pull request by tcolgate**

### CODE REVIEW

**Comment by tcolgate** [comment]
Fixes packet counts for #53 
The other dimensions are still dubious.
This also includes a fmt fix.

**Comment by grobie** [comment]
Hm, yeah. We increase the counter multiple times per packet in case of malformed/unexpected payload. I guess all the errors should be extracted into other metrics before this can be considered "fixed".

**Comment by SuperQ** [comment]
Ping, is still useful?  It needs a rebase.

**Comment by matthiasr** [comment]
You are right, the other dimensions are very dubious. Even so, calling it a "packet count" does not really do it justice. I went through and reworked everything previously covered by this metric in #106.

Since this PR has been inactive for a long time, and #106 is a superset of what it is trying to do, I'll go ahead and close this one.

**Pull request closed without merging**
